"""initial

Revision ID: 08720fee3fa0
Revises: 095585ffc767
Create Date: 2026-10-06 10:33:19.616373
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '08720fee3fa0'
down_revision: Union[str, None] = '095585ffc767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###