"""initial

Revision ID: 095585ffc767
Revises: 4c6085e9581c
Create Date: 2026-10-06 10:28:31.400955
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '095585ffc767'
down_revision: Union[str, None] = '4c6085e9581c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###