"""initial

Revision ID: 4c6085e9581c
Revises: 
Create Date: 2026-10-06 10:26:05.708638
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4c6085e9581c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_date', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.CheckConstraint('length(trim(display_name)) > 0', name='holidays_display_name_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_date')
    )
    op.create_table('saved_prediction_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_station_name', sa.String(), nullable=False),
    sa.Column('destination_station_name', sa.String(), nullable=False),
    sa.Column('journey_date', sa.String(), nullable=False),
    sa.Column('planned_departure_time', sa.String(), nullable=False),
    sa.Column('derived_day_type', sa.String(), nullable=False),
    sa.Column('crowding_level', sa.String(), nullable=False),
    sa.Column('is_leave_earlier_alert_shown', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.CheckConstraint('length(trim(destination_station_name)) > 0', name='results_dest_not_blank'),
    sa.CheckConstraint('length(trim(origin_station_name)) > 0', name='results_origin_not_blank'),
    sa.CheckConstraint('origin_station_name <> destination_station_name', name='results_stations_distinct'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('saved_prediction_results_crowding_level_journey_date_time_index', 'saved_prediction_results', ['crowding_level', 'journey_date', 'planned_departure_time', 'id'], unique=False)
    op.create_index('saved_prediction_results_journey_date_time_creation_index', 'saved_prediction_results', ['journey_date', 'planned_departure_time', 'id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='stations_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('stations_trimmed_name_unique', 'stations', ['name'], unique=False)
    op.create_table('timetable_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_station_id', sa.Integer(), nullable=False),
    sa.Column('destination_station_id', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('baseline_crowding_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.CheckConstraint('origin_station_id <> destination_station_id', name='patterns_stations_distinct'),
    sa.CheckConstraint('start_time < end_time', name='patterns_time_ordering'),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('timetable_patterns_destination_station_id_index', 'timetable_patterns', ['destination_station_id'], unique=False)
    op.create_index('timetable_patterns_origin_station_day_type_time_index', 'timetable_patterns', ['origin_station_id', 'destination_station_id', 'day_type', 'start_time', 'end_time'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('timetable_patterns_origin_station_day_type_time_index', table_name='timetable_patterns')
    op.drop_index('timetable_patterns_destination_station_id_index', table_name='timetable_patterns')
    op.drop_table('timetable_patterns')
    op.drop_index('stations_trimmed_name_unique', table_name='stations')
    op.drop_table('stations')
    op.drop_index('saved_prediction_results_journey_date_time_creation_index', table_name='saved_prediction_results')
    op.drop_index('saved_prediction_results_crowding_level_journey_date_time_index', table_name='saved_prediction_results')
    op.drop_table('saved_prediction_results')
    op.drop_table('public_holidays')
    # ### end Alembic commands ###