"""initial

Revision ID: 83cc58de64f5
Revises: 994c23d63b1c
Create Date: 2026-10-06 12:35:59.991675
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '83cc58de64f5'
down_revision: Union[str, None] = '994c23d63b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###