"""initial

Revision ID: 994c23d63b1c
Revises: 08720fee3fa0
Create Date: 2026-10-06 10:35:59.534666
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '994c23d63b1c'
down_revision: Union[str, None] = '08720fee3fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###