"""initial

Revision ID: cd996aa2378a
Revises: 83cc58de64f5
Create Date: 2026-10-06 13:54:58.441611
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cd996aa2378a'
down_revision: Union[str, None] = '83cc58de64f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###