"""initial

Revision ID: cdf18eea8d04
Revises: cd996aa2378a
Create Date: 2026-10-06 17:26:39.343033
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cdf18eea8d04'
down_revision: Union[str, None] = 'cd996aa2378a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###